{{- $fullName := include "generic.fullname" . -}}
{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/{{ .Values.externalSecrets.store.APIversion }}
kind: SecretStore
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
  {{- if .Values.appName }}
  annotations:
    argocd.argoproj.io/tracking-id: "{{ .Values.appName }}:external-secrets.io/SecretStore:{{ .Release.Namespace }}/{{ include "generic.fullname" . }}"
  {{- end }}
spec:
  provider:
    aws:
      region: "{{ .Values.externalSecrets.store.awsRegion }}"
      role: "{{ .Values.externalSecrets.store.fetchRoleARN }}"
      service: SecretsManager
{{- end }}